name: set-product-version
author: Release Engineering <rel-eng@hashicorp.com>
description: Automates setting product version

env:
  VERSION_FILE: ${{ .release/VERSION }}

runs:
  using: composite

  steps:
    - name: Check if Version File Exists
      uses: actions/checkout@v3
      shell: bash
      run: |
        FILE=$1
        if [ -f ${VERSION_FILE}]; then
          echo "File ${VERSION_FILE} exists."
        else
          echo "File ${VERSION_FILE} does not exist."
        fi

    - name: Set Product Version
      uses: actions/checkout@v3
      shell: bash
      run: |
        product_version=$(<.release/VERSION)
        echo "$product_version"
        whitespace=" |'"

        if ["$product_version" =~ $whitespace]; then
          echo "Whitespace detected in version string! Trimming down."
          echo "$product_version | sed 's/ //g'"
          product_version=$(echo "$product_version" | sed 's/ //g')
        else
          echo "No whitespace found in ${product_version}!"
        fi

    - name: Set output
      uses: actions/checkout@v3
      shell: bash
      run: echo "{product_version}={product_version}" >> GITHUB_OUTPUT